title: "Zoho Tricks"
email: anthonin@z-intel.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.svg'
favicon: 'assets/images/favicon.ico'
author: Zoho Tricks
paginate: 30
disqus: ''
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: text
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-KKDSHRR79J

# Authors
authors:
  zoho-tricks:
    name: Anthonin
    display_name: Anthonin
    avatar: ''
    email: anthonin@zoho-tricks.com
    web: https://zoho-tricks.com
    twitter: ''
    description: ""

# Social
social:
  instagram:
  facebook: 

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
