---
label: Default
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: text
  name: author
  label: author
- type: list
  name: categories
  label: categories
- type: file
  name: image
  label: image
- name: description
  type: text
  config:
    required: false
  label: Description
pages:
- _posts/zoho-workdrive-check-number-of-files.md
