---
label: Default
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: list
  name: categories
  label: categories
- name: description
  type: text
  config:
    required: false
  label: Description
- name: image
  type: text
  config:
    required: false
  label: image
- name: keywords
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: keywords
pages:
- _posts/2022-01-19-zoho-crm-related-list-archisnapper.md
- _posts/zoho-workdrive-check-number-of-files.md
