---
label: Default
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: list
  name: categories
  label: categories
- name: description
  type: text
  config:
    required: false
  label: Description
- name: image
  type: text
  config:
    required: false
  label: image
- name: keywords
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: keywords
pages:
- _posts/2021-04-11-zoho-deluge-format-number.md
- _posts/2021-06-18-zoho-deluge-create-folder-in-workdrive.md
- _posts/2021-11-26-zoho-deluge-post-request-in-json-format.md
- _posts/2021-12-09-zoho-deluge-for-loop.md
- _posts/2022-01-19-zoho-crm-related-list-archisnapper.md
- _posts/2022-09-30-zoho-catalyst-cron-function-books.md
- _posts/zoho-workdrive-check-number-of-files.md
